### ISSUE TITLE
Not able to install it

### ISSUE THREAD

**Issue by marcosberghahn** [aothman/hiscore#5]
I was not able to install it, here is my terminal log
```MyMac:~ mac$ pip install hiscore
Collecting hiscore
  Using cached hiscore-1.3.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rr/689sv74x7y95z5_klyb9qgbh0000gn/T/pip-build-9g_ktt8k/hiscore/setup.py", line 2, in <module>
        from hiscore import __version__, __maintainer__, __email__
      File "/private/var/folders/rr/689sv74x7y95z5_klyb9qgbh0000gn/T/pip-build-9g_ktt8k/hiscore/hiscore/__init__.py", line 8, in <module>
        from .engine import create, HiScoreEngine, Point
      File "/private/var/folders/rr/689sv74x7y95z5_klyb9qgbh0000gn/T/pip-build-9g_ktt8k/hiscore/hiscore/engine.py", line 107
        print e
              ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rr/689sv74x7y95z5_klyb9qgbh0000gn/T/pip-build-9g_ktt8k/hiscore/
MyMac:~ mac$```

**Comment by jaimergp** [comment]
Try with Python 2.7 instad of Python 3!

**Comment by troymyname** [comment]
I was having the same issue. I installed with Python 2.7 and it worked.
